--SNOWPIPE - Snowflakes's continuous data ingestion service
--Automatically loads files as soon as they arrive in cloud storage then stage

--CUSTOMERS
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.CUSTOMER_DETAILS_RAW
FROM
(
SELECT
$1,$2,$3,$4,$5,$6,$7,$8,$9,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_CSV_STAGE/customers/ 
)
PATTERN = '.*customers.*\.csv'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.CSV_FMT)
ON_ERROR = CONTINUE;

--products
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_PRODUCTS
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.PRODUCTS_RAW
FROM
(
SELECT  
$1,$2,$3,$4,$5,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_CSV_STAGE/products/
)
PATTERN = '.*products.*\.csv'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.CSV_FMT)
ON_ERROR = CONTINUE;

--stores
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_STORES
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.STORES_RAW
FROM
(
SELECT
$1,$2,$3,$4,$5,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_CSV_STAGE/stores/
)
PATTERN = '.*stores.*\.csv'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.CSV_FMT)
ON_ERROR = CONTINUE;


--sales header
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_SALES_HEADER
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.STORE_SALES_HEADER_RAW
FROM
(
SELECT
$1,$2,$3,$4,$5,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_CSV_STAGE/sales_header/
)
PATTERN = '.*sales_header.*\.csv'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.CSV_FMT)
ON_ERROR = CONTINUE;

--sales line items
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_SALES_LINE_ITEMS
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.STORE_SALES_LINE_ITEMS_RAW 
FROM
(
SELECT
$1,$2,$3,$4,$5,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_CSV_STAGE/sales_line_items/
)
PATTERN = '.*sales_line_items.*\.csv'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.CSV_FMT)
ON_ERROR = CONTINUE;

  
--loyality rules -JSON
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_LOYALTY_RULES
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.LOYALTY_RULES_RAW
FROM
(
SELECT
$1,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_JSON_STAGE/loyalty_rules/
)
PATTERN = '.*loyalty_rules.*\\.json'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.JSON_FMT)
ON_ERROR = CONTINUE;

--$1 → JSON object and METADATA$FILENAME → file name

--promotions
CREATE OR REPLACE PIPE RETAILPULSE_DB.BRONZE.PIPE_PROMOTIONS
AUTO_INGEST = TRUE
AS
COPY INTO RETAILPULSE_DB.BRONZE.PROMOTION_DETAILS_RAW
FROM
(
SELECT
$1,
METADATA$FILENAME
FROM @RETAILPULSE_DB.BRONZE.S3_JSON_STAGE/promotions/
)
PATTERN = '.*promotions.*\\.json'
FILE_FORMAT = (FORMAT_NAME = RETAILPULSE_DB.BRONZE.JSON_FMT)
ON_ERROR = CONTINUE;
