--Streams eenable CDC(Change data capture) it is useful for incremental data processing pipelines
CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.CUSTOMER_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.CUSTOMER_DETAILS_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.PRODUCTS_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.PRODUCTS_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.STORES_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.STORES_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.SALES_HEADER_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.STORE_SALES_HEADER_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.SALES_LINE_ITEMS_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.STORE_SALES_LINE_ITEMS_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.LOYALTY_RULES_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.LOYALTY_RULES_RAW;

CREATE OR REPLACE STREAM RETAILPULSE_DB.BRONZE.PROMOTIONS_STREAM
ON TABLE RETAILPULSE_DB.BRONZE.PROMOTION_DETAILS_RAW;



--STREAMS : TO CAPTURE INCREMENTAL DATA FROM SILVER
CREATE OR REPLACE STREAM SILVER.CUSTOMER_CLEAN_STREAM
ON TABLE SILVER.CUSTOMER_CLEAN;

CREATE OR REPLACE STREAM SILVER.PRODUCT_CLEAN_STREAM
ON TABLE SILVER.PRODUCT_CLEAN;

CREATE OR REPLACE STREAM SILVER.STORE_CLEAN_STREAM
ON TABLE SILVER.STORE_CLEAN;

CREATE OR REPLACE STREAM SILVER.SALES_HEADER_CLEAN_STREAM
ON TABLE SILVER.SALES_HEADER_CLEAN;

CREATE OR REPLACE STREAM SILVER.SALES_LINE_ITEMS_CLEAN_STREAM
ON TABLE SILVER.SALES_LINE_ITEMS_CLEAN;

CREATE OR REPLACE STREAM SILVER.PROMOTION_CLEAN_STREAM
ON TABLE SILVER.PROMOTION_CLEAN;

CREATE OR REPLACE STREAM SILVER.LOYALTY_RULES_CLEAN_STREAM
ON TABLE SILVER.LOYALTY_RULES_CLEAN;
