--STORAGE INTEGRATION
CREATE OR REPLACE STORAGE INTEGRATION AWS_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::745247897940:role/retail_s3'
STORAGE_ALLOWED_LOCATIONS = ('s3://retail-project-s3bucket/');

--Here we get AWS_IAM_USER_ARN and AWS_EXTERNAL_ID
DESC INTEGRATION AWS_S3_INT; 

--CREATING STAGE : Stages are the storage locations used to hold files before loading into snowflake tables
--CSV
CREATE OR REPLACE STAGE BRONZE.S3_CSV_STAGE
URL = 's3://retail-project-s3bucket/raw_csv/'
STORAGE_INTEGRATION = AWS_S3_INT
FILE_FORMAT = BRONZE.CSV_FMT;
  
--JSON
CREATE OR REPLACE STAGE BRONZE.S3_JSON_STAGE
URL = 's3://retail-project-s3bucket/raw_json/'
STORAGE_INTEGRATION = AWS_S3_INT
FILE_FORMAT = BRONZE.JSON_FMT; 
